name = "blog-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
# 初始管理员密码，部署后请在 Cloudflare Dashboard 的 Workers > Settings > Variables 中修改
ADMIN_PASSWORD = "admin123"
JWT_SECRET = "change-this-secret-in-production"

[[kv_namespaces]]
binding = "BLOG_KV"
id = "8b44160392164f2eac21dccccb5f91e8"
preview_id = "8b44160392164f2eac21dccccb5f91e8"
